"""motore — logica di gioco (ECS su esper, Processor, phase-gate, coda intenti).

NON importa MAI Textual (criterio C-2a). Parla con la vista solo via `contracts`.

Questa fase fissa le **fondamenta del ciclo di gioco** (FNC §6):
  - `FaseCorrente` — fase come componente-singleton nel World (fase.py);
  - `PhasedProcessor` + i tre bucket — phase-gate strutturale (phased.py);
  - `CodaIntenti` + `DrenaggioIntenti` — coda intenti drenata dal turno (intenti_coda.py);
  - `avvia_run` / `tick` / `collega_transizioni_fase` — assemblaggio e avanzamento (run.py).

Nessuna logica di gioco vera (sistemi di combattimento, status, generazione): arriva
dopo. Qui c'è lo scheletro deterministico su cui si agganciano.
"""

from .fase import (
    Fase,
    FaseCorrente,
    crea_entita_fase,
    imposta_fase,
    leggi_fase,
    in_combattimento,
    in_narrazione,
)
from .phased import (
    PhasedProcessor,
    SistemaSempreAttivo,
    SistemaSoloNarrazione,
    SistemaSoloCombattimento,
)
from .intenti_coda import (
    CodaIntenti,
    DrenaggioIntenti,
    MessaggioIntento,
    consuma_messaggi,
    messaggi_pendenti,
    travasa,
)
from .run import (
    PRIORITA_DRENAGGIO_INTENTI,
    BANDA_SOLO_COMBATTIMENTO,
    BANDA_SOLO_NARRAZIONE,
    BANDA_SEMPRE_ATTIVO,
    DT_TURNO,
    avvia_run,
    tick,
    collega_transizioni_fase,
)
from .calibrazione import (
    AP_MAX_MVP,
    S_CONTEST,
    MIN_COLPO,
    F_AUTOHIT,
    DELTA_BANDA,
    G_GRAZE,
    M_ARMATURA,
    M_TAGLIA,
    COEFF_ACC,
    W_FISICO,
    W_MAGIA,
    HP_BASE,
    K_HP,
    R_SOGLIA_CROLLO,
    CROLLO_INCREMENTO,
    MULT_MIN,
    MULT_MAX,
    primarie_da_archetipo,
    primarie_da_scalari,
)
from .scheda import ActionPoint, Protagonista, Scheda, crea_protagonista, protagonista
from .modificatori import (
    Modificatore,
    Modificatori,
    TipoMod,
    Origine,
    applica_modificatore,
    rimuovi_per_fonte,
    ResistenzaMod,
    Resistenze,
    applica_resistenza,
    rimuovi_resistenza_per_fonte,
)
from .statistiche import (
    Primarie,
    RigaStat,
    REGISTRY_STAT,
    FINALIZZA,
    Visibilita,
    Modificabilita,
    stat_eff,
    modificatori_su,
    modificatore_ammesso,
)
from .derivate import (
    max_hp,
    attacco,
    iniziativa,
    atk_eff,
    def_eff,
    eva_eff,
    acc_eff,
    cost_eff_come_centesimi,
    clampa_hp,
)
from .azione import Azione, Effetto, Danno, QuantitaDa
from .turno import TurnoAttivo, entita_attiva, segna_turno_attivo, azzera_turno_attivo
from .status import (
    Status,
    Veleno,
    Brucia,
    Rigenerazione,
    Stordito,
    Confusione,
    applica_status,
    SistemaVeleno,
    SistemaBrucia,
    SistemaRigenerazione,
    SistemaStordito,
)
from .combattimento import (
    DANNO_BASE,
    Nemico,
    PuntiVita,
    Combattente,
    SpecNemico,
    PianoIncontro,
    StatoCombattimento,
    calcola_iniziativa,
    decidi_azione_nemico,
    stato_combattimento,
    infliggi_danno,
    spawn_nemico,
    arruola_entita,
    esito_contest,
    check1,
    check2,
    mult_resistenza,
    risolvi_danno,
    SistemaTurnoCombattimento,
    SistemaDeathCheck,
    SistemaCrollo,
    collega_combattimento,
)
from .mutazione import OndataRinforzi, PianoRinforzi, SistemaRinforzi
from .catalogo import (
    REGISTRY_BLOCCHI,
    REGISTRY_ARCHETIPI,
    PROB_ANOMALIA,
    PROB_IMBOSCATA,
    ARCHETIPO_DEFAULT,
    DURATA_BLOCCO_DEFAULT,
    PRIMARIE_BASE_CARL,
    RANGO_GRADO,
    ProfiloArchetipo,
    Budget,
    Valenza,
    Risoluzione,
    FLAG_STATUS,
    rango_grado,
    prepara_contesto,
    soglia_classe,
    ancore_classe,
    carico_tick,
    gate_durata,
    valenza_di,
    risoluzione_di,
    e_unsafe,
    e_dannoso,
    tipi_status_noti,
)
from .prove import Prova, risolvi_prova
from .mappa import (
    Mappa,
    OpzioneScena,
    SistemaMovimento,
    componi_opzioni_scena,
    crea_mappa,
    discesa_consentita,
    dissolvi_mob,
    genera_topologia,
    mappa_corrente,
    mappa_da_dict,
    mappa_to_dict,
    mob_corrente,
    muovi,
    registra_mob,
    rimuovi_mob,
    scala_presente,
    segna_visitata,
    stanza_visitata,
    uscite,
)
from .design import (
    MobAttivo,
    PianoAttivo,
    StagioneAttiva,
    crea_stagione,
    design_piano_corrente,
    lint_registry,
    stagione_corrente,
)
from .piano import (
    LIVELLO_INIZIALE,
    ProfonditaPiano,
    TempoPiano,
    Piano,
    crea_profondita,
    crea_tempo_piano,
    livello_corrente,
    tempo_piano_corrente,
    attiva_discesa,
    SistemaDiscesa,
    raggiungibili,
    piano_completabile,
    valida_piano,
)
from .seme import SemeRun, crea_seme, master_seed
from .tempo import (
    TempoNonAvanzabile,
    SistemaTempoPiano,
    EsitoDado,
    RisultatoTick,
    RisultatoFastForward,
    ha_status_dannoso,
    ha_status_unsafe,
    puo_downtime,
    puo_passare_turno,
    tira_dado_evento,
    passa_turno,
    fast_forward,
)
from .narrazione import (
    RETRY_NARRAZIONE,
    RETRY_PROSA,
    MENU_FISSO,
    PROSA_NEUTRA,
    EntitaMob,
    RisultatoTurno,
    proietta_scheda,
    costruisci_prompt,
    valida_turno,
    fallback_turno,
    genera_prosa,
    procura_turno,
    esegui_turno_narrazione,
    istanzia_entita,
    materializza_turno,
    tenta_disimpegno,
    ingaggia_combattimento,
)
from .gm import (
    PREFISSO_GM,
    TIPO_RECORD_GM,
    EsitoTurnoGM,
    Fascicolo,
    MemoriaTurni,
    componi_fascicolo,
    esegui_turno_gm,
    firma_turno,
    messaggi_da_archivio,
    modula_stima_per_skill,
    prepara_riepilogo,
    riassunto_turno,
    sezione_fascicolo,
    spendi_tempo,
    stima_azione,
)
from . import persistenza
from .persistenza import (
    SCHEMA_VERSION,
    MODEL_ID_DEFAULT,
    NOME_RUN,
    NOME_DEFAULT,
    Archivio,
    Stato,
    CaricamentoFallito,
    VoceIndice,
    StatoCorrotto,
    VersioneIncompatibile,
    serializza_stato,
    applica_stato,
    salva_run,
    carica_da_disco,
    carica_archivio,
    invalida,
    indice_crawler,
    entra_run_nuova,
    carica_crawler,
    teardown_run,
    parcheggia_default,
)

__all__ = [
    # fase
    "Fase",
    "FaseCorrente",
    "crea_entita_fase",
    "leggi_fase",
    "imposta_fase",
    "in_combattimento",
    "in_narrazione",
    # phase-gate
    "PhasedProcessor",
    "SistemaSempreAttivo",
    "SistemaSoloNarrazione",
    "SistemaSoloCombattimento",
    # coda intenti
    "CodaIntenti",
    "DrenaggioIntenti",
    "MessaggioIntento",
    "consuma_messaggi",
    "messaggi_pendenti",
    "travasa",
    # assemblaggio
    "PRIORITA_DRENAGGIO_INTENTI",
    "BANDA_SOLO_COMBATTIMENTO",
    "BANDA_SOLO_NARRAZIONE",
    "BANDA_SEMPRE_ATTIVO",
    "DT_TURNO",
    "avvia_run",
    "tick",
    "collega_transizioni_fase",
    # scheda protagonista
    "Protagonista",
    "Scheda",
    "ActionPoint",
    "crea_protagonista",
    "protagonista",
    # calibrazione (Gruppo 2 §11): i VALORI placeholder, in un solo posto
    "AP_MAX_MVP",
    "S_CONTEST",
    "MIN_COLPO",
    "F_AUTOHIT",
    "DELTA_BANDA",
    "G_GRAZE",
    "M_ARMATURA",
    "M_TAGLIA",
    "COEFF_ACC",
    "W_FISICO",
    "W_MAGIA",
    "HP_BASE",
    "K_HP",
    "R_SOGLIA_CROLLO",
    "CROLLO_INCREMENTO",
    "MULT_MIN",
    "MULT_MAX",
    "primarie_da_archetipo",
    "primarie_da_scalari",
    # modello-stat (Gruppo 2): vettore primarie, registry, fold, modificatori, derivate
    "Primarie",
    "RigaStat",
    "REGISTRY_STAT",
    "FINALIZZA",
    "Visibilita",
    "Modificabilita",
    "stat_eff",
    "modificatori_su",
    "modificatore_ammesso",
    "Modificatore",
    "Modificatori",
    "TipoMod",
    "Origine",
    "applica_modificatore",
    "rimuovi_per_fonte",
    "ResistenzaMod",
    "Resistenze",
    "applica_resistenza",
    "rimuovi_resistenza_per_fonte",
    "max_hp",
    "attacco",
    "iniziativa",
    "atk_eff",
    "def_eff",
    "eva_eff",
    "acc_eff",
    "cost_eff_come_centesimi",
    "clampa_hp",
    # azione (Gruppo 2 §7): atomo spezzato, interno al motore (mai DTO)
    "Azione",
    "Effetto",
    "Danno",
    "QuantitaDa",
    # segnale di turno
    "TurnoAttivo",
    "entita_attiva",
    "segna_turno_attivo",
    "azzera_turno_attivo",
    # status
    "Status",
    "Veleno",
    "Brucia",
    "Rigenerazione",
    "Stordito",
    "Confusione",
    "applica_status",
    "SistemaVeleno",
    "SistemaBrucia",
    "SistemaRigenerazione",
    "SistemaStordito",
    # combattimento
    "DANNO_BASE",
    "Nemico",
    "PuntiVita",
    "Combattente",
    "SpecNemico",
    "PianoIncontro",
    "StatoCombattimento",
    "calcola_iniziativa",
    "decidi_azione_nemico",
    "stato_combattimento",
    "infliggi_danno",
    "spawn_nemico",
    "arruola_entita",
    "esito_contest",
    "check1",
    "check2",
    "mult_resistenza",
    "risolvi_danno",
    "SistemaTurnoCombattimento",
    "SistemaDeathCheck",
    "SistemaCrollo",
    "collega_combattimento",
    # mutazione intra-fase
    "OndataRinforzi",
    "PianoRinforzi",
    "SistemaRinforzi",
    # catalogo (faccia-motore: registry, formula, budget, ranghi, classi, tempo)
    "REGISTRY_BLOCCHI",
    "REGISTRY_ARCHETIPI",
    "PROB_ANOMALIA",
    "PROB_IMBOSCATA",
    "ARCHETIPO_DEFAULT",
    "DURATA_BLOCCO_DEFAULT",
    "PRIMARIE_BASE_CARL",
    "RANGO_GRADO",
    "ProfiloArchetipo",
    "Budget",
    "Valenza",
    "Risoluzione",
    "FLAG_STATUS",
    "rango_grado",
    "prepara_contesto",
    "soglia_classe",
    "ancore_classe",
    "carico_tick",
    "gate_durata",
    "valenza_di",
    "risoluzione_di",
    "e_unsafe",
    "e_dannoso",
    "tipi_status_noti",
    # prove di abilità
    "Prova",
    "risolvi_prova",
    # stagione attiva (design di contenuto congelato nella run)
    "MobAttivo",
    "PianoAttivo",
    "StagioneAttiva",
    "crea_stagione",
    "design_piano_corrente",
    "lint_registry",
    "stagione_corrente",
    # livello / piano / discesa
    "LIVELLO_INIZIALE",
    "ProfonditaPiano",
    "TempoPiano",
    "Piano",
    "crea_profondita",
    "crea_tempo_piano",
    "livello_corrente",
    "tempo_piano_corrente",
    "attiva_discesa",
    "SistemaDiscesa",
    # mappa (autorità spaziale: scena, movimento, persistenza slot esplorazione)
    "Mappa",
    "OpzioneScena",
    "SistemaMovimento",
    "componi_opzioni_scena",
    "crea_mappa",
    "discesa_consentita",
    "dissolvi_mob",
    "genera_topologia",
    "mappa_corrente",
    "mappa_da_dict",
    "mappa_to_dict",
    "mob_corrente",
    "muovi",
    "registra_mob",
    "rimuovi_mob",
    "scala_presente",
    "segna_visitata",
    "stanza_visitata",
    "uscite",
    "raggiungibili",
    "piano_completabile",
    "valida_piano",
    # master seed della run (persistenza H)
    "SemeRun",
    "crea_seme",
    "master_seed",
    # tempo (nodo J): scorrimento, dado-evento, fast-forward, passa-turno
    "TempoNonAvanzabile",
    "SistemaTempoPiano",
    "EsitoDado",
    "RisultatoTick",
    "RisultatoFastForward",
    "ha_status_dannoso",
    "ha_status_unsafe",
    "puo_downtime",
    "puo_passare_turno",
    "tira_dado_evento",
    "passa_turno",
    "fast_forward",
    # narrazione (socket, gate, fallback, materializzazione)
    "RETRY_NARRAZIONE",
    "RETRY_PROSA",
    "MENU_FISSO",
    "PROSA_NEUTRA",
    "EntitaMob",
    "RisultatoTurno",
    "proietta_scheda",
    "costruisci_prompt",
    "valida_turno",
    "fallback_turno",
    "genera_prosa",
    "procura_turno",
    "esegui_turno_narrazione",
    "istanzia_entita",
    "materializza_turno",
    "tenta_disimpegno",
    "ingaggia_combattimento",
    # pipeline GM (G §9.2: fan-out sotto il socket, una sola gating per turno)
    "PREFISSO_GM",
    "TIPO_RECORD_GM",
    "EsitoTurnoGM",
    "Fascicolo",
    "MemoriaTurni",
    "componi_fascicolo",
    "esegui_turno_gm",
    "firma_turno",
    "messaggi_da_archivio",
    "modula_stima_per_skill",
    "prepara_riepilogo",
    "riassunto_turno",
    "sezione_fascicolo",
    "spendi_tempo",
    "stima_azione",
    # persistenza (nodo H): UNICA autorità su current_world (ESP §0.1)
    "persistenza",
    "SCHEMA_VERSION",
    "MODEL_ID_DEFAULT",
    "NOME_RUN",
    "NOME_DEFAULT",
    "Archivio",
    "Stato",
    "CaricamentoFallito",
    "VoceIndice",
    "StatoCorrotto",
    "VersioneIncompatibile",
    "serializza_stato",
    "applica_stato",
    "salva_run",
    "carica_da_disco",
    "carica_archivio",
    "invalida",
    "indice_crawler",
    "entra_run_nuova",
    "carica_crawler",
    "teardown_run",
    "parcheggia_default",
]
