"""contracts — la membrana motore ⇄ vista (IC §2) e il contratto AI↔motore (nodo F).

ZERO dipendenze di progetto: **solo stdlib + Pydantic** (F-2). NON importa esper,
Textual, provider (il layer), motore, adattatore. È il vocabolario condiviso:
  - il **bus tipizzato** di progetto (ESP §5) — `bus.py`;
  - gli **eventi di dominio** (motore → vista) — `eventi.py`;
  - gli **intenti** del giocatore (vista → motore) — `intenti.py`;
  - lo **schema Pydantic** del contratto AI↔motore (nodo F) — `schema.py`;
  - l'**interfaccia provider** (solo firma/Protocol, PLK §2) — `provider.py`.

Motore e vista importano *questo*, e non si importano mai a vicenda (C-3).
"""

from .bus import BusEventi, Handler
from .eventi import (
    Entita,
    EventoDominio,
    EncounterStarted,
    ColpoInferto,
    CombatResolved,
    EffettoStatus,
    MortePersonaggio,
    AnomalyTriggered,
    CrolloDungeon,
    DiscesaPiano,
    DisimpegnoScena,
    TransizioneZona,
    OggettoTrovato,
    StatusApplicato,
    StatusSvanito,
    RiposoConcluso,
    TurnoSaltato,
)
from .intenti import (
    Intento,
    IntentoCombattimento,
    IntentoEsplorazione,
    PlayerChoseOption,
    PlayerSiMuove,
    PlayerTentaProva,
    PlayerAttraversa,
    PlayerDiscende,
    PlayerEquipaggia,
    PlayerToglie,
)
from .schema import (
    ArchetipoId,
    Grado,
    StatId,
    Blocco,
    TipoDanno,
    StileAttacco,
    TipoAzione,
    ClasseProva,
    ClasseBeneficio,
    Taglia,
    CategoriaArmatura,
    CategoriaPng,
    Fascia,
    FasciaCosto,
    FasciaPotenza,
    FasciaRicarica,
    FasciaRischio,
    SedeAccessorio,
    Durata,
    BossGenerato,
    EntitaGenerata,
    Frequenza,
    LottoBossGenerati,
    LottoMosseAutorate,
    LottoOggettiAutorati,
    LottoStatusProposti,
    StatusProposto,
    ModificatoreAutorato,
    MossaAutorata,
    NemicoSperimentale,
    OggettoAutorato,
    OggettoGenerato,
    PezzoUnico,
    SkillGenerata,
    RuoloMob,
    TabellaProceduraleGen,
    TabellaSpawnGenerata,
    TierTerritorio,
    TipoStanza,
    TurnoNarrazione,
    VoceSpawnGenerata,
    Flavor,
    IntenzioneScena,
    TonoScena,
    Ideazione,
    BattutaScena,
    BloccoScena,
    EsitoScena,
    InquadramentoProva,
)
from .memoria import (
    DocumentoMemoria,
    MemoriaNarrativa,
    TipoDocumento,
)
from .wiki import (
    ApprovazioneVoce,
    ContestoScena,
    LinkVoce,
    PropostaWiki,
    ProvenienzaVoce,
    RegiaVoce,
    RESTRITTIVITA_REGIA,
    RevisioneVoce,
    ScopeVoce,
    SegretezzaVoce,
    TipoVoce,
    VoceSlice,
    VoceWiki,
    WikiMaster,
    WikiSlice,
)
from .esito import (
    ClassificaGiorno,
    EsitoRun,
    FantasmaRun,
    NecrologioCrawler,
    VoceClassifica,
    seed_del_giorno,
)
from .contenuti import (
    ArchetipoAsset,
    AssetVista,
    BudgetDesign,
    EffettoDati,
    FabbricaAsset,
    MobAsset,
    ModificatoreDati,
    MossaAsset,
    OggettoAsset,
    ParteAffisso,
    ParteBase,
    ParteFamiglia,
    PianoAsset,
    PianoRisolto,
    ProfiloArchetipoDati,
    Stagione,
    StagioneRisolta,
    TabellaBossProcedurali,
    TabellaSpawn,
    TabellaSpawnRisolta,
    TerritorioDesign,
    TerritorioRisolto,
    VoceSpawn,
    VoceSpawnRisolta,
)
from .hub import CrawlerVista
from .proiezione import (
    EquipVista,
    ProgressioneVista,
    SchedaProiezione,
    SchedaVista,
    SkillVista,
    SlotEquip,
    SLOT_ARMATURA,
    SLOT_IMPUGNATI,
)
from .vista import (
    FattiScena,
    FattiScontro,
    GradoEsito,
    MessaggioGM,
    OpzioneVista,
    ProsaFuoriBanda,
    ProvaVista,
    RiepilogoAzione,
    SnapshotVista,
    StimaAzione,
    TempoVista,
    Terminale,
    TipoProsa,
)
from .provider import Provider, TCandidato

__all__ = [
    # strato sovra-run (Fase A; B/C/D preparati, non consumati)
    "ClassificaGiorno",
    "EsitoRun",
    "FantasmaRun",
    "NecrologioCrawler",
    "VoceClassifica",
    "seed_del_giorno",
    # wiki del master (W1)
    "ApprovazioneVoce",
    "ContestoScena",
    "LinkVoce",
    "PropostaWiki",
    "ProvenienzaVoce",
    "RegiaVoce",
    "RESTRITTIVITA_REGIA",
    "RevisioneVoce",
    "ScopeVoce",
    "SegretezzaVoce",
    "TipoVoce",
    "VoceSlice",
    "VoceWiki",
    "WikiMaster",
    "WikiSlice",
    # bus
    "BusEventi",
    "Handler",
    # eventi di dominio
    "Entita",
    "EventoDominio",
    "EncounterStarted",
    "ColpoInferto",
    "CombatResolved",
    "EffettoStatus",
    "MortePersonaggio",
    "AnomalyTriggered",
    "CrolloDungeon",
    "DiscesaPiano",
    "DisimpegnoScena",
    "TransizioneZona",
    "OggettoTrovato",
    "StatusApplicato",
    "StatusSvanito",
    "TurnoSaltato",
    "RiposoConcluso",
    # intenti
    "Intento",
    "IntentoCombattimento",
    "IntentoEsplorazione",
    "PlayerSiMuove",
    "PlayerChoseOption",
    "PlayerTentaProva",
    "PlayerAttraversa",
    "PlayerDiscende",
    "PlayerEquipaggia",
    "PlayerToglie",
    "Taglia",
    "CategoriaArmatura",
    "CategoriaPng",
    "Fascia",
    "FasciaCosto",
    "FasciaPotenza",
    "FasciaRicarica",
    "FasciaRischio",
    "SedeAccessorio",
    # schema AI↔motore
    "ArchetipoId",
    "Grado",
    "StatId",
    "Blocco",
    "TipoDanno",
    "StileAttacco",
    "TipoAzione",
    "ClasseProva",
    "ClasseBeneficio",
    "Durata",
    "EntitaGenerata",
    "TurnoNarrazione",
    "Flavor",
    "IntenzioneScena",
    "TonoScena",
    "Ideazione",
    "BattutaScena",
    "BloccoScena",
    "EsitoScena",
    "InquadramentoProva",
    # proiezione scheda (sola lettura) + scheda per la UI + hub
    "SchedaProiezione",
    "SchedaVista",
    "SkillVista",
    "EquipVista",
    "SlotEquip",
    "SLOT_ARMATURA",
    "SLOT_IMPUGNATI",
    "ProgressioneVista",
    "CrawlerVista",
    # contenuti dello show (asset riusabili + forme risolte)
    "AssetVista",
    "BudgetDesign",
    "ArchetipoAsset",
    "EffettoDati",
    "FabbricaAsset",
    "MobAsset",
    "ParteAffisso",
    "ParteBase",
    "ParteFamiglia",
    "ModificatoreDati",
    "MossaAsset",
    "OggettoAsset",
    "PianoAsset",
    "ProfiloArchetipoDati",
    "PianoRisolto",
    "Stagione",
    "StagioneRisolta",
    "BossGenerato",
    "Frequenza",
    "LottoBossGenerati",
    "LottoMosseAutorate",
    "LottoOggettiAutorati",
    "LottoStatusProposti",
    "StatusProposto",
    "MossaAutorata",
    "ModificatoreAutorato",
    "NemicoSperimentale",
    "OggettoAutorato",
    "OggettoGenerato",
    "PezzoUnico",
    "SkillGenerata",
    "RuoloMob",
    "TabellaProceduraleGen",
    "TabellaSpawnGenerata",
    "TierTerritorio",
    "TipoStanza",
    "VoceSpawnGenerata",
    "TabellaBossProcedurali",
    "TabellaSpawn",
    "TabellaSpawnRisolta",
    "TerritorioDesign",
    "TerritorioRisolto",
    "VoceSpawn",
    "VoceSpawnRisolta",
    # snapshot di rendering per la vista
    "DocumentoMemoria",
    "MemoriaNarrativa",
    "TipoDocumento",
    "OpzioneVista",
    "SnapshotVista",
    "ProsaFuoriBanda",
    "TipoProsa",
    "Terminale",
    "MessaggioGM",
    "TempoVista",
    "ProvaVista",
    "GradoEsito",
    "StimaAzione",
    "RiepilogoAzione",
    "FattiScena",
    "FattiScontro",
    # provider
    "Provider",
    "TCandidato",
]
